server:
  port: 8804
spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database: MYSQL
    openInView: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 25
          batch_versioned_data: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        show_sql: true
        format_sql: true
  # TODO: Datasource config
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_URL:localhost}:3306/hierarchy_company_db?useUnicode=yes&characterEncoding=utf-8&useSSL=true&requireSSL=true"
    username: "${HIERARCHY_COMPANY_DB_USER:root}"
    password: "${HIERARCHY_COMPANY_DB_PWD:password}"
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      minimum-idle: ${DB_MIN_IDLE:2}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:4}
      idle-timeout: ${DB_IDLE_TIMEOUT:10000}
      max-lifetime: ${DB_MAX_LIFETIME:600000}
      auto-commit: true
      data-source-properties:
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        cache-prep-stmts: true
        use-server-prep-stmts: true

jwt:
  secret: javainuse