version: '3.5'

services:

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: hierarchy_company_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: userroot
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - hierarchy-mysql:/var/lib/mysql

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    container_name: pma1
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "28000:80"

  demo:
    image: hierarchy
    container_name: hierarchy
    depends_on:
      - db
    ports:
      - "8804:8804"
    environment:
      DB_URL: host.docker.internal
      SPRING_PROFILES_ACTIVE: local

volumes:
  hierarchy-mysql:
    driver: local
  hierarchy-pgadmin:
    driver: local